SELECT CART_ID
FROM (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME='Milk'
    UNION ALL
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME='Yogurt'
) CT
GROUP BY CART_ID
HAVING COUNT(CART_ID)=2
ORDER BY 1