WITH RECURSIVE ECOLI_LEVEL AS (
    SELECT ID, 1 AS LEVEL
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, EL.LEVEL + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_LEVEL EL
        ON E.PARENT_ID = EL.ID
    WHERE EL.LEVEL < 3
)
SELECT ID
FROM ECOLI_LEVEL
WHERE LEVEL = 3
ORDER BY ID;