WITH RECURSIVE ECOLI_LEVEL 
AS (
    SELECT ID, PARENT_ID, 1 AS LEVEL
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, EL.LEVEL + 1
    FROM ECOLI_DATA E INNER JOIN ECOLI_LEVEL EL ON E.PARENT_ID = EL.ID
)
SELECT ID
FROM ECOLI_LEVEL
WHERE LEVEL = 3
ORDER BY ID;
