SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A, (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) M
WHERE A.FOOD_TYPE = M.FOOD_TYPE AND A.FAVORITES = M.FAVORITES
ORDER BY FOOD_TYPE DESC