WITH RENTED AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '20221016' BETWEEN DATE_FORMAT(START_DATE, '%Y%m%d') AND DATE_FORMAT(END_DATE, '%Y%m%d')
)
SELECT 
    DISTINCT CAR_ID, 
    IF (CAR_ID IN (SELECT CAR_ID FROM RENTED), '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;
