SELECT F.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * P.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT F, (
    SELECT PRODUCT_ID, AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
) AS P
WHERE F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY F.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC