SELECT 
    F.PRODUCT_ID,
    F.PRODUCT_NAME,
    SUM(F.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT F
JOIN FOOD_ORDER O
    ON F.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE >= '2022-05-01'
  AND O.PRODUCE_DATE < '2022-06-01'
GROUP BY F.PRODUCT_ID, F.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID ASC;