WITH RENTAL_PERIOD AS (
    SELECT *, TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 AS PERIOD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    JOIN CAR_RENTAL_COMPANY_CAR USING(CAR_ID)
),
EXACT_DURATION_TYPE AS (
    SELECT *,
        CASE WHEN PERIOD < 7 THEN NULL
            WHEN PERIOD < 30 THEN '7일 이상'
            WHEN PERIOD < 90 THEN '30일 이상'
            ELSE '90일 이상'
        END AS E_DURATION_TYPE
    FROM RENTAL_PERIOD
),
EXACT_DISCOUNT_RATE AS (
    SELECT T.CAR_TYPE, HISTORY_ID, PERIOD, DAILY_FEE, COALESCE(DISCOUNT_RATE, 0) AS DISCOUNT_RATE
    FROM EXACT_DURATION_TYPE T
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON T.CAR_TYPE = P.CAR_TYPE AND E_DURATION_TYPE = DURATION_TYPE
    GROUP BY HISTORY_ID
)
SELECT HISTORY_ID, FLOOR(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * PERIOD) AS FEE
FROM EXACT_DISCOUNT_RATE
WHERE CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC