WITH RENTAL AS (
    SELECT 
        H.HISTORY_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1 AS PERIOD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C 
        ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)
SELECT 
    R.HISTORY_ID,
    FLOOR(R.DAILY_FEE * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100) * R.PERIOD) AS FEE
FROM RENTAL R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON R.CAR_TYPE = P.CAR_TYPE
    AND (
        R.PERIOD BETWEEN 7 AND 29 AND P.DURATION_TYPE = '7일 이상'
        OR R.PERIOD BETWEEN 30 AND 89 AND P.DURATION_TYPE = '30일 이상'
        OR R.PERIOD >= 90 AND P.DURATION_TYPE = '90일 이상'
    )
ORDER BY FEE DESC, R.HISTORY_ID DESC;