SELECT 
    E.EMP_NO, 
    E.EMP_NAME, 
    CASE
        WHEN AVG(G.SCORE) >= 96 THEN 'S'
        WHEN AVG(G.SCORE) >= 90 THEN 'A'
        WHEN AVG(G.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE, 
    CASE
        WHEN AVG(G.SCORE) >= 96 THEN E.SAL * 20 / 100
        WHEN AVG(G.SCORE) >= 90 THEN E.SAL * 15 / 100
        WHEN AVG(G.SCORE) >= 80 THEN E.SAL * 10 / 100
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES E
    INNER JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
    INNER JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO, E.EMP_NAME, E.SAL
ORDER BY E.EMP_NO;