WITH PARENT_INFO AS (
    SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY, T.ITEM_ID AS CHILD_ITEM_ID
    FROM ITEM_INFO I INNER JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
)
SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO C INNER JOIN PARENT_INFO P ON C.ITEM_ID = P.CHILD_ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC;