WITH GENOTYPES AS (
    SELECT 
        CHILD.ID, 
        CHILD.GENOTYPE, 
        PARENT.GENOTYPE PARENT_GENOTYPE
    FROM ECOLI_DATA CHILD 
        LEFT JOIN ECOLI_DATA PARENT 
            ON CHILD.PARENT_ID = PARENT.ID
)
SELECT *
FROM GENOTYPES
WHERE GENOTYPE & PARENT_GENOTYPE = PARENT_GENOTYPE
ORDER BY ID;