WITH RENTAL_IN_PERIOD AS (
    SELECT CAR_ID, START_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y%m') BETWEEN '202208' AND '202210'
),
QUALIFIED_CAR AS (
    SELECT CAR_ID
    FROM RENTAL_IN_PERIOD
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM RENTAL_IN_PERIOD
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM QUALIFIED_CAR
)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC;