WITH TOTAL_FISH_INFO AS (
    SELECT FISH_NAME, LENGTH
    FROM FISH_INFO FI INNER JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
)
SELECT COUNT(*) AS FISH_COUNT
FROM TOTAL_FISH_INFO
WHERE FISH_NAME IN ('BASS', 'SNAPPER');