WITH MAX_LENGTH_FISH_INFO AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO I 
    INNER JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    INNER JOIN MAX_LENGTH_FISH_INFO M ON I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH
ORDER BY ID;