SELECT
    SUM(G.SCORE) AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES E
    JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
    JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR = 2022
GROUP BY
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
HAVING SUM(G.SCORE) = (
    SELECT MAX(TOTAL_SCORE)
    FROM (
        SELECT SUM(SCORE) AS TOTAL_SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) T
);