SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS F, (
    SELECT CATEGORY AS MCATEGORY, MAX(PRICE) AS MPRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) M
WHERE F.PRICE = M.MPRICE AND F.CATEGORY = M.MCATEGORY
ORDER BY MAX_PRICE DESC