WITH FRONT_END AS (SELECT BIT_OR(CODE) AS CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'),
     PYTHON    AS (SELECT BIT_OR(CODE) AS CODE FROM SKILLCODES WHERE NAME = 'Python'),
     CSHARP    AS (SELECT BIT_OR(CODE) AS CODE FROM SKILLCODES WHERE NAME = 'C#')
SELECT
    CASE
        WHEN SKILL_CODE & (SELECT CODE FROM FRONT_END) > 0
            AND SKILL_CODE & (SELECT CODE FROM PYTHON) > 0 THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM CSHARP) > 0 THEN 'B'
        WHEN SKILL_CODE & (SELECT CODE FROM FRONT_END) > 0 THEN 'C'
    END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS
WHERE
    SKILL_CODE & (SELECT CODE FROM FRONT_END) > 0
    OR SKILL_CODE & (SELECT CODE FROM CSHARP) > 0
ORDER BY GRADE, ID;